// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1tHT1EupmibUhacJFGQmjlUO6ac8bVEs',
    appId: '1:35506012542:web:cce84fa0076f322cdef32f',
    messagingSenderId: '35506012542',
    projectId: 'uno-stack-2by2',
    authDomain: 'uno-stack-2by2.firebaseapp.com',
    databaseURL: 'https://uno-stack-2by2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uno-stack-2by2.firebasestorage.app',
    measurementId: 'G-DCRVCZ4FED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf5-cagibXsBZxwKHoIfPWgmzOIAxQD0A',
    appId: '1:35506012542:android:8a0c40cd6594d0c5def32f',
    messagingSenderId: '35506012542',
    projectId: 'uno-stack-2by2',
    databaseURL: 'https://uno-stack-2by2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uno-stack-2by2.firebasestorage.app',
  );
}
